name: bookings_africa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.17.4
  http: ^0.12.2
  fluttericon: ^1.0.7
  google_fonts: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/HelveticaNeue Light.ttf
    - family: HelveticaB
      fonts:
        - asset: fonts/Helvetica Neu Bold.ttf
    - family: HelveticaM
      fonts:
        - asset: fonts/HelveticaNeue Medium.ttf
